#!/bin/bash

#read themes from config file
themes=()

while read line; do
	themes+=($line)
done < ~/.config/themeSwitcher/themes.conf

n=${#themes[@]}

k=$(8-$n) #add empty strings at the end of themes

for i in $(seq 1 $k); do
	themes+=" "
done

printf '\e[?1049h'
printf '\e[?25l'
clear

printf "   \u250C              \u2510\n     Choose theme\n   \u2514              \u2518\n\n"

for i in {0..8}; do
	printf " \u2502 ${themes[$i]}\n"
done


choice=0

branch="$(git rev-parse --abbrev-ref HEAD)"

for i in ${!themes[@]}; do
       if [[ "${themes[$i]}" = "$branch" ]]; then
	       choice=$i;
       fi
done

printf "\e[%d;4H> ${themes[$choice]}" $((5+$choice)) 

#echo -e -n "\e[5;4H> $branch\e[0m"

while read -rsn1 ui; do



    case "$ui" in
    $'\x1b')    
        read -rsn1 -t 0.1 char
        if [[ "$char" == "[" ]]; then
            read -r -s -n 1 -t 0.1 char
            case "$char" in
            "B"|"C") # right
		choice=$(( ($choice+1) % $n  ));;
            "A"|"D") # left
		choice=$(( ((($choice-1) % $n) + $n) % $n  ));;
            esac
	    
	    for i in {0..8}; do
		    printf "\e[%d;4H${themes[$i]}  " $((5+$i))
	    done

	    printf "\e[%d;4H> ${themes[$choice]}" $((5+$choice))

        fi
        # Flush "stdin" with 0.1  sec timeout.
        read -rsn5 -t 0.1
        ;;
    $'\0')
    	break ;;     

    q)
	printf '\e[?1049l'
	printf '\e[?25h'
    	exit 0;;
    esac
done

git checkout ${themes[$choice]}

printf '\e[?1049l'
printf '\e[?25h'
exit 0
